# Generated by Django 2.2.2 on 2019-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='ユーザID')),
                ('display_name', models.CharField(max_length=255, verbose_name='表示名')),
                ('age', models.IntegerField(default=-1, verbose_name='年齢')),
                ('occupation', models.IntegerField(default=-1, verbose_name='職業')),
                ('is_rock', models.IntegerField(default=-1, verbose_name='施錠状態')),
                ('latitude', models.FloatField(default=-1.0, verbose_name='変換前の緯度')),
                ('longitude', models.FloatField(default=-1.0, verbose_name='変換前の経度')),
                ('conLatitude', models.FloatField(default=-1.0, verbose_name='変換後の緯度')),
                ('conLongitude', models.FloatField(default=-1.0, verbose_name='変換後の経度')),
                ('pattern', models.IntegerField(default=-1, verbose_name='メッセージパターン')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('display_name', models.CharField(max_length=255, verbose_name='表示名')),
                ('age', models.IntegerField(default=-1, verbose_name='年齢')),
                ('occupation', models.IntegerField(default=-1, verbose_name='職業')),
                ('is_rock', models.IntegerField(default=-1, verbose_name='施錠状態')),
                ('latitude', models.FloatField(default=-1.0, verbose_name='変換前の緯度')),
                ('longitude', models.FloatField(default=-1.0, verbose_name='変換前の経度')),
                ('conLatitude', models.FloatField(default=-1.0, verbose_name='変換後の緯度')),
                ('conLongitude', models.FloatField(default=-1.0, verbose_name='変換後の経度')),
                ('month', models.IntegerField(default=-1, verbose_name='月')),
                ('time', models.IntegerField(default=-1, verbose_name='時間')),
                ('score', models.FloatField(default=-1.0, verbose_name='安全スコア')),
            ],
        ),
    ]
